name: $(VersionNumberMajor).$(VersionNumberMinor)$(Rev:.rrrr)

parameters:
- name: BuildConfiguration
  displayName: Release or Debug
  type: string
  default: Release
  values:
  - Release
  - Debug

- name: BuildPool
  displayName: 'Build Pool'
  type: string
  default: 'DCT Build Pool'
  values:
  - 'DCT Build Pool'
  - 'DCT'
  
- name: BuildPoolDemand
  displayName: 'Build Pool Demand'
  type: string
  default: 'IsBuildServer'
  values:
  - 'IsBuildServer'
  - 'IsBuildServer_Old'
  - 'IsBuildServer_TEST'
  - 'IsBuildServer_PCTEST'

variables:  
  VersionNumberMajor: '0'
  VersionNumberMinor: '0'
  
stages:
- stage: Build
  displayName: Build stage
  variables:
    NugetFeed: 'dct-pkg'  
    NugetVersion: '5.8.0'
    DotnetCoreVersion: '2.2.x'
    
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: ${{ parameters.BuildPool }} 
      demands:
      - ${{ parameters.BuildPoolDemand }} 

    steps:
    - task: UseDotNet@2
      enabled: false
      displayName: 'Use .NET Core sdk : $(DotnetCoreVersion)'
      inputs:
        packageType: sdk
        version: $(DotnetCoreVersion)
        performMultiLevelLookup: true

    - task: NuGetToolInstaller@0
      enabled: false
      displayName: 'Use NuGet : $(NugetVersion)'
      inputs:
        versionSpec: '>= $(NugetVersion)'
        checkLatest: true
        
    - task: DotNetCoreInstaller@0
      enabled: false
      displayName: 'Use .NET Core sdk 2.2.106'
      inputs:
        version: 2.2.106

#********************************************************************************
# Build and Restore
#******************************************************************************** 
    - task: DotNetCoreCLI@2
      displayName: 'Restore Monitoring Metrics Function'
      inputs:
        command: restore
        projects: **/*.Monitoring.Metrics.Function.csproj
        configuration: ${{ parameters.BuildConfiguration }}
        feedsToUse: 'select'
        vstsFeed: '$(NugetFeed)'

    - task: MSBuild@1
      displayName: 'Build Monitoring.Metrics.Function'
      inputs:
        solution: **/.Payments.Monitoring.Metrics.Function.csproj
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/p:version=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber) /p:OutputPath=$(Build.ArtifactStagingDirectory)/MetricsFunction /p:configuration=Release'
        clean: true
        maximumCpuCount: true
        logProjectEvents: true
        createLogFile: true
  
#********************************************************************************
# Copy Nuget Packages into Aftifact Folder
#********************************************************************************   
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: '**/*.nupkg'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/ProviderPayments'

#********************************************************************************
# Publish Artifacts
#********************************************************************************    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Packages'
      inputs:
        artifact: MetricFunction
        PathtoPublish: $(Build.ArtifactStagingDirectory)/MetricsFunction
